dmel=read.delim("")

dmel_evalue=do.call(rbind,mclapply(split(dmel,dmel$Trinity5_Id),function(x) x[which.min(x$E_value),]))
dmel_cov_grt_50=do.call(rbind,lapply(split(dmel,dmel$Trinity5_Id),function(x) x[(x$Coverage_percentage >= 50),]))
dim(dmel_cov_grt_50)
dmel_cov_grt_50_evalue=do.call(rbind,lapply(split(dmel_cov_grt_50,dmel_cov_grt_50$Trinity5_Id),function(x) x[which.min(x$E_value),]))
dim(dmel_cov_grt_50_evalue)
dmel_cov_less_50=do.call(rbind,lapply(split(dmel,dmel$Trinity5_Id),function(x) x[(x$Coverage_percentage < 50),]))
dim(dmel_cov_less_50)
dmel_cov_less_50_evalue=do.call(rbind,lapply(split(dmel_cov_less_50,dmel_cov_less_50$Trinity5_Id),function(x) x[which.min(x$E_value),]))
dim(dmel_cov_less_50_evalue)
dmel_cov_evalue=rbind(dmel_cov_grt_50_evalue,dmel_cov_less_50_evalue)
dmel_cov_evalue=do.call(rbind,lapply(split(dmel_cov_evalue,dmel_cov_evalue$Trinity5_Id),function(x) x[which.min(x$E_value),]))
dim(dmel_cov_evalue)
