mouse_evalue=do.call(rbind,lapply(split(mouse,mouse$Trinity5_Id),function(x) x[which.min(x$E_value),]))
dim(mouse_evalue)
mouse_cov_grt_50=do.call(rbind,lapply(split(mouse,mouse$Trinity5_Id),function(x) x[(x$Coverage_percentage >= 50),]))
dim(mouse_cov_grt_50)
mouse_cov_grt_50_evalue=do.call(rbind,lapply(split(mouse_cov_grt_50,mouse_cov_grt_50$Trinity5_Id),function(x) x[which.min(x$E_value),]))
dim(mouse_cov_grt_50_evalue)
mouse_cov_less_50=do.call(rbind,lapply(split(mouse,mouse$Trinity5_Id),function(x) x[(x$Coverage_percentage < 50),]))
dim(mouse_cov_less_50)
mouse_cov_less_50_evalue=do.call(rbind,lapply(split(mouse_cov_less_50,mouse_cov_less_50$Trinity5_Id),function(x) x[which.min(x$E_value),]))
dim(mouse_cov_less_50_evalue)
mouse_cov_evalue=rbind(mouse_cov_grt_50_evalue,mouse_cov_less_50_evalue)
mouse_cov_evalue=do.call(rbind,lapply(split(mouse_cov_evalue,mouse_cov_evalue$Trinity5_Id),function(x) x[which.min(x$E_value),]))
dim(mouse_cov_evalue)